; Rename this file to platformio_override.ini and set your WiFi credentials here, e.g. "MyWiFi" and "MyPassword"
; This file is ignored by git, so your WiFi credentials won't be shared on GitHub
; You can also set other parameters here, e.g. monitor_speed, upload_speed, monitor_filters, build_flags, etc. that will override the defaults in platformio.ini

[defaults]
; Config to use (onboard) I2S audio codec ES8311
monitor_speed = ${common.monitor_speed}
upload_speed  = ${common.upload_speed}
monitor_filters = ${common.monitor_filters}
build_flags     = ${common.build_flags}
    -D _SSID='"MySSID"'         ;Set WiFi credentials in this file, e.g. "MyWiFi"
    -D _PW='"MyPassword"'       ;Set WiFi password in this file, e.g. "MyPassword"
    -D USE_ES8311               ;Use ES8311 audio codec, comment out to use built-in DAC instead